pub const CREATE_USER_ACTION: &str = "CREATE_USER";
pub const CHANGE_OTHERS_PASSWORD_ACTION: &str = "CHANGE_OTHERS_PASSWORD";
pub const LIST_USERS_ACTION: &str = "LIST_USERS";
pub const DELETE_USER_ACTION: &str = "DELETE_USER";
