pub const CREATE_CATEGORY_ACTION: &str = "CREATE_CATEGORY_ACTION";
pub const REPLACE_CATEGORY_ACTION: &str = "REPLACE_CATEGORY_ACTION";
pub const DELETE_RECURSIVE_CATEGORY_ACTION: &str = "DELETE_RECURSIVE_CATEGORY_ACTION";